### ISSUE TITLE
dcurve: integrate trust bonus score into linear QF

### ISSUE THREAD

**Issue by thelostone-mc** [dcgtc/dgrants#100]
### Description 

While running a dGrants round. 
The `dcurve` package should be able to fetch the trust bonus score of the contributor's address ( hosted on gitcoin )  while determining the distribution. Until `DID` are generated and are issues `NFT`/stored on-chain, a temporary solution here would be integrating an API 

- [x] introduce a new endpoint on gitcoin to fetch the trust bonus score https://github.com/gitcoinco/web/pull/9349
- [x] identify wherein `linear.ts` would we'd add the trust bonus score 
- [x] wire in the API call and make the changes
- [ ] @frankchen07 to validate algo with big dataset

**Comment by frankchen07** [comment]
finished testing 

- saturation point hit (different combinations of contributions) with possible zero grant (1 contrib)
- saturation point not hit (different combinations of contributions) with possible zero grant (1 contrib)
