### ISSUE TITLE
Add Grant Logo To Metadata

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#119]
This issue is dependent on #86. It expands the metadata stored for a Grant to include a Grant Logo, and displays the grant logo on the site in various contexts where it should be.

Incorporation of the logos should directionally follow the [figma designs](https://www.figma.com/file/sUQSYyPfooqTcVdajfZm0t/dgrants?node-id=92%3A80), but does not need to be precise. A proper re-working of the relevant components will occur with #112.

- [x] When a user creates a Grant, the grant form should have an optional field that allows them to select a logo image, and validates:
    - [x] dimension : 1920x1080 ( 16:9 )
    - [x] formats : png or svg . no jpg as its to big and not a format for logos but for photos .
    - [x] filesize : max 200kb ( thats an edgecase already, regular it should be like 15kb - 80kb )
- [x] Before the grant is created:
    - [x] The logo image should be uploaded to IPFS first
    - [x] The cloudflare IPFS gateway URL using the logo CID should be included in the Grant Metadata using the field `logo`. See the schema example below
    - [x] The rest of grant creation process now continues, i.e. the grant metadata is uploaded to IPFS, then the user submits the transaction to create the Grant, which includes the metadata CID
- [x] Grant logos should be displayed in Grant list contexts, i.e. on the registry page
- [x] The Grant logo should be displayed on the Grant Detail Page
- [x] Fetching of Grant logos should be non-blocking to the UI, and fail gracefully with a placeholder in each instance where it doesn't succeed.
- [x] Our fixture data should be updated to metadata that includes the logo field pointing to valid images on IPFS

#### Updated Grant Metadata Schema

```json
{
    "name": "My Grant",
    "description": "There are many Grants, but this one is mine",
    "logo": "https://cloudflare-ipfs.com/ipfs/QmaKj8z3icu3UFqXK4NXy7Mcch9kCPZJA128gP4pa4fQQM"
}
```

**Comment by mds1** [comment]
For whoever tackles this issue: we already have an unused `logoURI` parameter in the `GrantMetadata` type definition. We used the name `logoURI` to be consistent with what TokenLists call the field that contains the URL to a token's logo (see `SUPPORTED_TOKENS` definition for an example)

**Comment by mds1** [comment]
The `logoURI` is optional in that type definition, since we never discussed whether or not an image should be required to create a new grant

**Comment by scco** [comment]
if possible it should be checked for filesize and format and dimensions .

dimension : 1920x1080   ( 16:9 )
formats :  png or svg .  no jpg as its to big and not a format for logos but for photos .
filesize : max 200kb  ( thats an edgecase already, regular it should be like 15kb - 80kb )
