### ISSUE TITLE
Header UI Conversion

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#134]
- [ ] https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/LayoutHeader.vue

**Comment by carletex** [comment]
Hey @gdixon I'm taking a look at the LayoutHeader if that's ok.

**Comment by carletex** [comment]
Working on BaseHeader also. I'll create a single PR with both components.

**Comment by carletex** [comment]
Done in #162
