### ISSUE TITLE
Expand Grant Metadata to Include Basic Properties

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#145]
Currently, the minimal grant metadata schema is limited to:

```json
{
    "name": "My Grant",
    "description": "There are many Grants, but this one is mine",
    "logo": "https://cloudflare-ipfs.com/ipfs/QmaKj8z3icu3UFqXK4NXy7Mcch9kCPZJA128gP4pa4fQQM"
}
```

We want to expand the schema to include some of the basic grant properties, most importantly properties that will point externally to other sources of information about the grant, namely:

- [x] The project website
- [x] Twitter Handle
- [x] Github

The updated schema should look like:

```json
{
    "name": "My Grant",
    "description": "There are many Grants, but this one is mine",
    "logo": "https://cloudflare-ipfs.com/ipfs/QmaKj8z3icu3UFqXK4NXy7Mcch9kCPZJA128gP4pa4fQQM",
    "properties": {
        "projectWebsite": "https://gitcoin.co",
        "projectGithub": "https://github.com/dcgtc/dgrants",
        "twitterHandle": "https://twitter.com/GitcoinDAO"
     }
}
```

The frontend should also be updated to accommodate these properties:

- [x] Optional fields on the create/edit grant form with basic validation, including URL for the GitHub & Twitter links
- [x] Properly add the fields to the metadata before uploading it to IPFS
    - [x] Each individual property is optional, but the `properties` top level key should always be present. The app should handle the absence of any individual property gracefully.
- [x] Display these fields on the Grant Detail page

**Comment by mds1** [comment]
Right now we have `logoURI` as optional also, so I just want to clarify which items in the metadata schema are optional vs. required. You could argue `name` is the only required field, but maybe we want to require other fields also? I only mention it here because this feels like a good issue to clarify / update that in
