### ISSUE TITLE
App does not render when served from IPFS

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#178]
When you run yarn build then deploy the app/dist folder to IPFS and attempt to load the app, the app does not render. I specifically have tested through Fleek deployment.

You can see one example deployment here: https://royal-dawn-9397.on.fleek.co/

The developer console reveals an issue with brorand.Rand:
```
Uncaught TypeError: brorand.Rand is not a constructor
    at new MillerRabin$2 (vendor.b0604c86.js:41)
    at vendor.b0604c86.js:41
```

<img width="629" alt="Screen Shot 2021-09-03 at 6 07 06 PM" src="https://user-images.githubusercontent.com/1074345/132069414-c623f4be-ca38-4b0c-b354-93cfc3e0ad90.png">

**Comment by apbendi** [comment]
Maybe we should try deploying to a typical centralized hosting service like Netlify for example, just to determine whether this is a problem with our build, or something to do with Fleek/IPFS.

**Comment by mds1** [comment]
This is coming from the [`miller-rabin`](https://github.com/indutny/miller-rabin) package. There's a related issue here: https://github.com/indutny/miller-rabin/issues/10

Here's why this package is installed, though I haven't looked into where it's used. I agree with @apbendi that that's a good next step, though I suspect we'll still get the same error

```
$ yarn why miller-rabin
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "miller-rabin"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "miller-rabin@4.0.1"
info Reasons this module exists
   - "_project_#@dgrants#app#crypto-browserify#diffie-hellman" depends on it
   - Hoisted from "_project_#@dgrants#app#crypto-browserify#diffie-hellman#miller-rabin"
   - Hoisted from "_project_#@dgrants#contracts#hardhat#@ethereumjs#blockchain#@ethereumjs#ethash#miller-rabin"
   - Hoisted from "_project_#@dgrants#contracts#ethereum-waffle#@ethereum-waffle#provider#ganache-core#ethereumjs-vm#ethereumjs-blockchain#ethashjs#miller-rabin"
info Disk size without dependencies: "44KB"
info Disk size with unique dependencies: "176KB"
info Disk size with transitive dependencies: "176KB"
info Number of shared dependencies: 2
✨  Done in 1.07s.
```
