### ISSUE TITLE
Rename Infura env variable for clarity

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#18]
In our .env files, the VITA_INFURA_API_KEY variable could be renamed to VITA_INFURA_PROJECT_ID (or VITA_INFURA_ID) to match the way that the value is named on Infura. For consistency, the INFURA_ID variable could be renamed to INFURA_PROJECT_ID (or left alone if we use VITA_INFURA_ID).

**Comment by wildmolasses** [comment]
also, is there a downside to removing the VITA prefixes? Or, if the fact they're being used on the frontend is an important signal, renaming them to `FRONTEND_`?

**Comment by mds1** [comment]
`VITE`*😛

But yea we need to keep that prefix. The prefix is used by Vite so it can automatically detect which environment variables to include in the build. See the `.env Files` section [here](https://vitejs.dev/guide/env-and-mode.html#env-files) for more info. This is the same as what React does with the [`REACT_APP_` prefix](https://create-react-app.dev/docs/adding-custom-environment-variables/)

We can rename it to `VITE_INFURA_ID` and that should be clear + match the contracts directory naming
