### ISSUE TITLE
Implement Grants Round Factory

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#19]
This issue is dependent on #17 

We will use the factory pattern to allow users to create new `GrantRound` instance. The factory should:

- [ ] Take all the parameters needed to initialize a new `GrantRound` and deploy one via a public method call
- [ ] Emit an event with the parameters when it does so
- [ ] Remove existing `GrantRounds` contract and tests

Questions:

* Should the factory method or the `GrantRound` constructor do any sanity checking of the address provided as the ERC20 token? For example, calling the `symbol` method, which would cause revert if the address passed was not an ERC20 implementation.

**Comment by mds1** [comment]
> Should we use minimal proxies for the GrantRound when creating them? Doing so would significantly reduce the cost of deploying a new GrantRound instance, but slightly increase the cost of interacting with the instance— most importantly when a user makes a contribution

Deploying the current `GrantRound` contract in #17 costs 973,698 gas (~$110 at $1920 ETH and 60 gwei). I think that is cheap enough that whoever is running the grant round can fund that cost, that way donors save 2600 gas to delegatecall to the implementation + the calldata cost in the delegatecall (and calldata may be large if donating to lots of grants at once through the GrantRound contract)

**Comment by mds1** [comment]
Following up on the above comment, the gas cost to pass the calldata for 100 grants from the proxy to the implementation, assuming we pass a grantId and an amount with 2 slots, is the cost of a CALLDATACOPY (since delegatecall operates on memory, the calldata is copied to memory) is—and this is a very rough estimate—about 1200 extra gas (based on https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a3-copy-operations)

So total cost to users of using minimal proxies is about 2600+1200 = 3800 extra gas per bulk donation

**Comment by mds1** [comment]
> Should the Factory itself store any reference to the GrantRound instances deployed through it? Is there any utility to this? Leaning toward no.

Agreed here. I can't yet think of a reason why we might need the factory to know about round instances

**Comment by thelostone-mc** [comment]
Quick question here for both of you + @phutchins 
If the RoundFactory doesn't store references to the GrantRound Contract.
What other benefits do we stand do again by having a Grant Round Factory which eventually creates a grant Round   as opposed to having the entity/user just create a Grant Round Contract directly ?

**Comment by mds1** [comment]
Even if the factory doesn't store a reference in storage to the rounds it deploys, the benefits are:
1. The factory still tracks a history of all deployed rounds through event logs, for off-chain queries
2. It's simpler for users/frontends to deploy a new round by calling a method on a factory contract than encoding constructor arguments and deploying the bytecode directly

**Comment by apbendi** [comment]
Sounds like we're leaning toward:

* No minimal proxies
* No factory storage

I will update the issue to reflect this. Please push back if you feel I'm off.

**Comment by mds1** [comment]
> Should the factory method or the GrantRound constructor do any sanity checking of the address provided as the ERC20 token? For example, calling the symbol method, which would cause revert if the address passed was not an ERC20 implementation.

We never answered this, but I think we should add some verification in the `GrantRound` constructor. Unless anyone disagrees, I'll plan to add that to the branch I'm working on for the factory contract.

Technically name and symbol are optional in ERC-20, but would likely be an odd token choice if it didn't have a name or symbol. But perhaps we just check `totalSupply > 0` to make sure it's a token with some existing supply

Also planning to check:
- end time > start time
- registry.grantCount() >0 (i.e. just check it doesn't revert)

Anything else you can think of?

**Comment by apbendi** [comment]
This all seems reasonable to me @mds1. I don't see anything else as of now.
