### ISSUE TITLE
Edit Grant Screen Is Broken

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#206]
Not sure what happened but looks like something broke or we had a regression with the Edit Grant screen. Field labels are gone so it's not possible to tell what you're editing.

<img width="1007" alt="Screen Shot 2021-09-10 at 3 58 13 PM" src="https://user-images.githubusercontent.com/1479802/132910808-1d1d988d-4520-487f-b79f-24d230d8bc9d.png">

**Comment by scco** [comment]
hint : see GrantRegistryNewGrant.vue  how to use the Component <InputRow>  to create forms

**Comment by thelostone-mc** [comment]
@scco Could you do a run through the UI and document what all are broken due to the changes you made in UI 
Given we are to go live this week -> we probably want to avoid breaking changes coming in
