### ISSUE TITLE
Discuss: How To Support Multiple Token Donations

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#22]
The in-progress implementation of `GrantRound` defines a single token— selected by the Round owner at deployment— which is used for all contributions, including matching pool contributions, grant contributions, and the subsequent payout of matching contributions after the round is over.

For at least the case of grant contributions— and possibly for matching pool contributions as well— we want to support users being able to give in the token of their choice. There are at least two broad approaches for doing so.

One approach would be to allow the user to specify the token they're donating at the time of a contribution in the `GrantRound` itself, and accept the token donation regardless of this address. 

Another approach would be to retain a single accounting token for each `GrantRound`, and instead swap the token for the accounting token before paying it to the Grant or adding it to the matching Pool. This could be done internally on the `GrantRound`, using an external wrapper contract, or using a more advanced approach like a `delegatecall` to a swapping strategy contract defined at deploy time (in order to allow alternative or upgradeable swapping strategies in future Rounds).

This issue is for discussing and weighing the tradeoffs involved in each approach  before making a decision on how to implement it.

**Comment by apbendi** [comment]
At first blush I lean heavily toward the swap approach, preferably implemented outside the `GrantRound` contract in some way (either a wrapper or strategy). Here's my thinking as to why:

* It keeps the `GrantRound` contract simple, and easy to reason about and test, and provides a clear separation of concerns
* It reduces the attack/bug surface of the `GrantRound` contract— i.e. if the `GrantRound` deployer can choose the donation token, there is far less risk of an issue arising due to a non-standard (ex: rebasing) or intentionally malicious (ex: re-entrancy) token contract.
* It reduces the complexity of the off-chain matching calculations, and decreases difficulty of making them verifiable and reproducible, by removing the need to include contemporaneous price data for each donation made.
  * The accounting is done completely in the specified accounting token
  * There are no concerns / questions about determining the price of a token. A simple example: imagine a large quantity of a low liquidity token is donated. In the direct-donation case, if we fetch and use the instantaneous price, the dollar value of the donation may appear enormous and skew matching amounts dramatically. On the other hand, if the user is forced to (automagically) swap their low-liquidity token into the accounting token, the price impact from the AMM is accounted for and the matching script has no concern.
* It's better for Grantees not to have their funds split across many different tokens, which they have to liquidate individually, and some of which may be below "dust" amounts (i.e. not worth the cost to swap to something liquid). 
* The experience for the user can (I believe) be no different than in the case where a user can donate arbitrary tokens.

Happy to hear arguments for the other approach, or where my assessment of the swap approach might be wrong!

**Comment by thelostone-mc** [comment]
Hmm i see what you're saying and I agree with having it outside the GrantRound contract.
Having a swap contract allows everyone to contribute to both the pool  + the grant which is a win.

I do have few questions however in terms of the flow 

**Questions:**

- Does this mean the would be handled by the dapp (cause the user would have to sign an extra signature to do the swap ?)
- Would it fair to say all contributions which go to a Grant within a GrantRound will be **ALWAYS BE THE SAME TOKEN**
- Having it all in the same token makes generating the distribution curve easier like what you said @apbendi. 
    - You don't need to store the USD  value at the time of contribution etc
    - If GrantRound uses DOGE , then since all contributions happens via DOGE -> we don't care about how the market fluctuates  
- I'm worried about how the contributions Events would look in this case -> if I contributed BADGE tokens to a grant via GrantRound which accepts only DOGE. Would it looks weird that my contribution history states i transferred DOGE when in face I used BADGER 
- If the swap happens -> is this something we want to be stored as well saying the user originally contributed in DAI (this need not be on chain , it could reside on the dApp)

**Comment by apbendi** [comment]
> Does this mean the would be handled by the dapp (cause the user would have to sign an extra signature to do the swap ?)

Not necessarily (although sending two txs is one way you *could* do it). I think it could be done with a specialized `swapAndDonate` method, that we would code, which would handle both actions in a single transaction.

> Would it fair to say all contributions which go to a Grant within a GrantRound will be ALWAYS BE THE SAME TOKEN

Yes. So if RoundA chooses Dai for it's token, the Grant payee will receive only Dai donations inbound for RoundA, whereas if RoundB chooses DOGE, the Grant payee will receive only DOGE donations inbound for RoundB.

> You don't need to store the USD value at the time of contribution etc
> If GrantRound uses DOGE , then since all contributions happens via DOGE -> we don't care about how the market fluctuates

Yes, I think this is the really nice thing about this approach. The matching/payouts all happen in the same token. No price oracles are needed. In other words, 1 DOGE = 1 DOGE ;)

> I'm worried about how the contributions Events would look in this case -> if I contributed BADGE tokens to a grant via GrantRound which accepts only DOGE. Would it looks weird that my contribution history states i transferred DOGE when in face I used BADGER

This is a good point, but if we use a wrapper contract that includes a `swapAndContribute` method, that method could itself emit events, which the Dapp could then fetch and use to populate the UI. That said, it's not clear to me what the best display WOULD be. Perhaps show the donated token, with the conversion included as well? `Donated 1 DOGE (0.25 Dai)`

> If the swap happens -> is this something we want to be stored as well saying the user originally contributed in DAI (this need not be on chain , it could reside on the dApp)

Again if we have a wrapper contract of any kind that can emit events, this could be handled here.

### Additional questions:

One more point here is how this interacts with #20. It could be that the `swapAndDonate` method lives on the Router.

**Comment by mds1** [comment]
While this is dependent on #20 like mentioned above, I do think it might be worth just having a `swapAndDonate` method live in the same contract as the regular `donate` method to save gas—you save on CALL gas costs, as well as removing additional approvals and transfers if your swap happens through a separate contract.

If each `GrantRound` instance is deployed from a factory, it's easy to upgrade swap logic (and anything else in the grant round contract) by just making the `grantRoundImplementation` address an argument to a `factory.createGrantRound()` method. This means anyone can create a grant round with any implementation logic they want, which is a nice side effect. (Downside is users now need to verify the implementation before contributing to a round)

> This is a good point, but if we use a wrapper contract that includes a swapAndContribute method, that method could itself emit events, which the Dapp could then fetch and use to populate the UI. That said, it's not clear to me what the best display WOULD be. Perhaps show the donated token, with the conversion included as well? Donated 1 DOGE (0.25 Dai)

I think this works, though there still will be some extra frontend work to parse the donation data. Something like this seems like the way you'd do it:
- I `batchDonate` to 10 grants, which swaps 100 BADGER for 50 DAI
- `Swap` event emits that I swapped 100 BADGER for 50 DAI
- `DonationSent` event emits the DAI amounts sent to each of the 10 grants
- Frontend has to use the exchange rate inferred from the `Swap` event to convert units in each `DonationSent` event

Not a huge issue though, definitely doable

**Comment by apbendi** [comment]
Good point @mds1, that does make the offchain work a little more complicated, but still doable I think, like you said. I'd suggest when we get there, we should revisit the need for this feature at all, that is, do we *really* need to show the original donation token vs. just showing the Round's native token? If so, what's driving that requirement? But yeah, that's a discussion for a later point.

If there no objections, I think should proceed under the assumption that we will take the single accounting token approach, and the discussion then moves to the implementation details, which are largely driven by our discussion on #20. Does anyone disagree?

**Comment by mds1** [comment]
That all sounds good to me, agreed on that path forward

**Comment by apbendi** [comment]
Closed with #40
