### ISSUE TITLE
Remove the "Equivalent To" row in the cart conversion if all donations are in Dai

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#220]
It feels odd to have the "Equivalent To" section in the cart if all donations are already denominated in the token selected. The UI should remove this row in this case.

<img width="1140" alt="Screen Shot 2021-09-13 at 9 53 31 AM" src="https://user-images.githubusercontent.com/1479802/133096624-13ff9f4d-83af-4afc-9599-adf876257b15.png">

**Comment by phutchins** [comment]
Resolved by #229
