### ISSUE TITLE
Get Tests Running In CI

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#23]
Set up GitHub Actions for CI. The full monorepo test suite should run. Preferably, the tests would run when a PR was opened and/or udpated.

**Comment by wildmolasses** [comment]
Sounds good. As part of this we will need to provision the env files. I'll create a new issue for repo owner ( presumably @phutchins ) to add the env variables to the repo settings.

**Comment by wildmolasses** [comment]
OK, we don't need envs after all :+1:

Question, besides running tests, do we want to run the linter?

**Comment by phutchins** [comment]
I'd say yes to the linter.
