### ISSUE TITLE
When staying on grant detail page, it refreshes every few seconds

### ISSUE THREAD

**Issue by mds1** [dcgtc/dgrants#236]
Steps to reproduce:
1. Checkout the `l2-config` branch
2. Switch wallet to Rinkeby
3. Run `yarn && yarn dev`
4. Open app and view a grant
5. Keep the Grant detail page open long enough and you'll see the below

I'd guess this happens on `main` also, because the behavior is likely occuring every time there's a new block and we poll for updated data. But we don't notice it on `main`  because with Hardhat there's no blocks that are automatically mined

![CleanShot 2021-09-14 at 13 57 57](https://user-images.githubusercontent.com/17163988/133332919-0181fdc1-9703-45fa-b269-c9b26bc9cc12.gif)

**Comment by phutchins** [comment]
This is fixed by #229 .
