### ISSUE TITLE
feat: add clear grant logo + preload image on edit form

### ISSUE THREAD

**Issue by thelostone-mc** [dcgtc/dgrants#241]
#### Description 

- [x] Ability to remove image on edit/create grant page
- [x] Ability to preview/preload the image on the edit form when a user edits the grant

These changes would need to made around:
- Grant Creation
- Grant Edit
- BaseImageUpload

**Comment by scco** [comment]
i spend a bit time to checkout the edit a grant in current main branch and helped out, get my planed UI regarding image-upload / display uploaded images  into  the form to edit a grant.

<img width="1689" alt="Bildschirmfoto 2021-09-16 um 16 10 11" src="https://user-images.githubusercontent.com/569641/133629128-2af495d4-ceca-4099-9810-d102fe0731bb.png">

### Component : ImageRow
- tryed to do the simple work on this already,
you just have to make the delete (X-Icon) click in this component 
is doing outside of the component the "delete"
- when there is no image uploaded, this component can hide.

### Component : BaseUpload
- on click : regular "file explorer have to open" to select an image. 
this needs probably some work to make it work.
- on drag images on it : yea the hard part i guess ... 
but you have the UI - hurray :) 

### Little changes on `GrantRegistryGrantDetail.vue`
- I have noticed some "flex ... css" in line `116` what is not needed. i removed these classes, as this form should take up full width without any left right paddings ... 
- removed on line `120` the text-left class.  now as in App.vue is no extra css code from old times, its not needed anymore.

Happy to help as best as i can on questions - hope this helps a bit - Checkout here :

https://github.com/dcgtc/dgrants/tree/richard-imageupload-ui

**Comment by mk1r** [comment]
[ ] ask a user to provide a large enough image (with different ratios)
[ ] let the user choose the content to crop out of it to fit 16:9 ratio
[ ] resize image on the client side as long as we have source image with high enough quality
