### ISSUE TITLE
bug: Grants and GrantRounds will not display if a wallet has not been selected

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#246]

**Comment by apbendi** [comment]
Seems not to be using the default provider when user does not have a connected wallet or is on the wrong chain.

**Comment by mds1** [comment]
Will be fixed as part of my PR for #242, so @gdixon re-assigning this to me

**Comment by mds1** [comment]
Fix here if you need to cherry-pick it for your own branch: https://github.com/dcgtc/dgrants/commit/40a9b206e1cabaced9e77764970c3e02a92f8e94
