### ISSUE TITLE
Implement top level grant filter

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#253]
As a stop gap prior to having a grant curation system in place, we should implement a hard coded list of grants that are white-listed for being displayed on the dGrants system.

Requirements
- List should be hosted on IPFS OR provide an ENV variable to configure white-listed grant ids
- Should be able to add grants by their ID to an array I.E. [0,1,2,3,5,10]
- Should be able to change the setting to show all grants - Empty array should signify show all grants

**Comment by apbendi** [comment]
For MVP, probably fine to go with a JSON file with lists by chainId.
