### ISSUE TITLE
UI: Grant creation approval notice after creation

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#254]
After a grant is created, the user should be informed that their grant will not show up immediately and will only be displayed after review and approval.

**Requirements**
- After submitting a grant, user should be redirected to /dgrants/grant-submitted page (or other appropriate name)
- grant-submitted page should say "Thank you for your grant submission! \n Your grant has been queue'd for review and upon approval will be visible to everyone. \n Average time to review is less than 24 hours."
- No button should be necessary to go back home as the navigation should provide all that is necessary

**Comment by mk1r** [comment]
any suggestions on how to handle this? should we add in a message on the confirmation page?

**Comment by thelostone-mc** [comment]
^ cc @scco 

@mk1r I think we should use the UI toasters we have (the one in which errors show up)
The only question here is -> does this mean on completion of creation of grant we redirect them to grant list page ?

**Comment by mds1** [comment]
> @mk1r I think we should use the UI toasters we have (the one in which errors show up)

Agreed, this is the simplest and works for now. We can always do something fancier later if we need to.

However, @scco, it looks like the notification toasters are styled to look identical regardless of which `alertType` is used, which seems not ideal—i.e. there's no way to distinguish between positive, neutral, or negative alerts without reading the message

> The other question here is -> does this mean on completion of creation of grant we redirect them to grant list page ?
@phutchins

I'd say yes, not sure of a better page to redirect to

**Comment by scco** [comment]
my proposal for

**NOW**

on successfully submit a grant , redirect to a blank page 

/dgrants/grant-successfully-submited  
what just have some generic "thank you we review your grant" + what ever button to home view.

**LATER** 
i planed to have routes for a user/ethereumaddress to views like :
"my profile", "my favorites", "my grants", "my settings"  ...

so later we would want to redirect from a successfully submited grant to the "my grants" view, 
where a  user should then see his new created grant with a "under review" label . 
and in best case with NO under review label - as we do a decentral grants application where everybody can create grants.


i would suggest to just create a new route + grant-successfully-submited.vue for now, and let me style it a bit. + ping me on what branch it is so i can help out here.

**Comment by phutchins** [comment]
Added spec/requirements to initial comment.

**Comment by mk1r** [comment]
closing in favor of discussion #320
