### ISSUE TITLE
Track Form States By Network ID

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#261]
Disable buttons that would trigger a transaction when network id is not `DGRANTS_CHAIN_ID`. Should be implemented globally in the wallet store and referenced in individual components.

- [ ] Cart
- [ ] Create Grant
- [ ] Edit Grant
- [ ] Others...?

**Comment by carletex** [comment]
We already have `isSupportedNetwork` on the wallet store, but it might not work for us, since it assumes "valid" when we don't have network information:

```js
  const isSupportedNetwork = computed(
    () => (network.value ? DGRANTS_CHAIN_ID === network.value.chainId : true) // assume valid if we have no network information
  );
```

If this doesn't work for us, we can create a `isValidNetwork` property.

> Should be implemented globally in the wallet store and referenced in individual components.

Instead of using isSupportedNetwork/isValidNetwork on every individual component, we could also create a <TxButton> component to wrap this logic.

@apbendi @mds1 thoughts?

**Comment by mds1** [comment]
Agreed you can't use `isSupportedNetwork` for the reason you mentioned. You'll want to add a new (very similar) computed property such as

```typescript
const isCorrectNetwork = computed(() => (network.value && DGRANTS_CHAIN_ID === network.value.chainId));
```

We can then return that from the store, and in the various components they should just add an `isCorrectNetwork.value` check to the logic that determines whether a button should be disabled

**Comment by mds1** [comment]
> Instead of using isSupportedNetwork/isValidNetwork on every individual component, we could also create a <TxButton> component to wrap this logic.

Kind of the same net effect here, in that you either need `TxButton` in every component or `isCorrectNetwork` in every component's tx buttons. IMO using `isCorrectNetwork` is a little cleaner since it doesn't add a new file with very little content

**Comment by carletex** [comment]
Make sense. Thanks Matt!
