### ISSUE TITLE
Fix type checks so build succeeds

### ISSUE THREAD

**Issue by mds1** [dcgtc/dgrants#27]
Running `yarn build` from the app folder fails with various TS errors. 
- These TS errors don't show up when building for dev mode, i.e. `yarn dev`
- These TS errors don't show up when running `yarn lint`
- - These TS errors don't show up in the VSCode UI
- Building directly with `yarn vite build` succeeds
- The errors are thrown from the `vue-tsc --noEmit` check in `yarn build`

@wildmolasses Curious to hear your inputs on the best way to handle this so those TS errors surface sooner, whether that's in the VSCode UI, the dev console, or during linting

**Comment by wildmolasses** [comment]
@mds1 why are we using vue-tsc? unless there's a particular reason, i think vue 3 already works with typescript, so we can just use tsc.

**Comment by mds1** [comment]
I'll ask the opposite question—if Vue 3 works with TypeScipt, why is vue-tsc the only package picking up these lint errors? 😛. As shown in the images below, the lint errors it outputs are correct, so I'm surprised VSCode isn't reporting them with red squiggles.

I think the answer is that TS does not work with Vue SFCs (single file components), and vue-tsc is needed to get TS working with SFCs. More info here: https://github.com/vitejs/vite/issues/749

![image](https://user-images.githubusercontent.com/17163988/126401910-395cac3b-ce5b-446c-9efa-7154b0d927f8.png)
![image](https://user-images.githubusercontent.com/17163988/126401915-a3035108-f013-4567-9db7-58c9a1ccfdce.png)

Assuming we do need vue-tsc, we want to run it more frequently than just on `yarn build`, because we don't want PRs to get merged to main that don't build because of TS errors. Perhaps we add the `vue-tsc --noEmit` check to `yarn lint` and run the linter as part of CI, or as a pre-commit or pre-push hook.

If that makes sense, and you want to start a branch with those changes, I can then make the corresponding code changes to remove the lint errors

**Comment by apbendi** [comment]
Note: we also want to turn on linting as part of when a PR is opened.

**Comment by wildmolasses** [comment]
Thanks Matt for calling out the typescript <> SFC issue. Here you can see that vetur is properly picking up these type issues. Is this the case on your machine as well?

![Screen Shot 2021-07-22 at 11 04 04 AM](https://user-images.githubusercontent.com/5423313/126671238-6112056d-d4f7-440f-817a-97a0fa819817.png)

I'm happy with the solution of including `vue-tsc --noEmit` in app's `lint` script, and including a lint step in the workflow action!

**Comment by mds1** [comment]
> I'm happy with the solution of including `vue-tsc --noEmit` in app's `lint` script, and including a lint step in the workflow action!

Yes that works for me! Wondering if it's worth also adding as a commit/push hook or if it's too slow? That way any issues are caught sooner in the development flow

**Comment by wildmolasses** [comment]
OK, i've PRed a change to the workflow file that runs `vue-tsc --noEmit` into app's `lint` script & adds the lint step to the workflow file 👍 . You can see that the action fails as expected. I'll reassign this issue back to you to fix the vue TS errors -- I started to look into them but I'm not as familiar with computed refs. That said I'm happy to help resolve these errors via pairing!

**Comment by apbendi** [comment]
closed by #49
