### ISSUE TITLE
reskin / style the wallet connect modal

### ISSUE THREAD

**Issue by scco** [dcgtc/dgrants#288]
<img width="521" alt="Bildschirmfoto 2021-09-24 um 18 38 41" src="https://user-images.githubusercontent.com/569641/134710611-84a16d0e-d718-4c8e-a8e9-7413a82269ef.png">

haven't looked in the codebase for this modal, 
but i would love to try to reskin it to fit our minimal layout.

as i have basicaly all the icons for common web3 providers, would love to use these too.

**Comment by mk1r** [comment]
also, maybe we should be using web3modal here? then we can allow walletconnect and other wallets as well - and can it can be styled well too

**Comment by mds1** [comment]
I'd recommend sticking with onboard.js. It supports a lot more wallets than web3modal, gives you the ability to customize a lot of the appearance, and (to me, at least) looks nicer/cleaner.

@scco docs for styling this modal are here: https://docs.blocknative.com/onboard#customizing-css

I don't think we should change the wallet icons though (even though I do like your icons!). The wallet icons/logos are pretty much standardized across all apps I've seen, so if it were changed, I know I'd find that confusing and I'd guess other users would too

**Comment by chnejohnson** [comment]
Hello guys,

Just pass by and see this issue. I'm developing Vue 3 library for the wallet connect, so welcome to check out [vue-dapp](https://github.com/chnejohnson/vue-dapp)!
