### ISSUE TITLE
GrantRound UI Spec

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#29]
- [ ] Round Detail Page
    - [x] route: `/dgrants/rounds/:address` where `:address` is the hex address of a `GrantRound` contract instance
    - [ ] Displays the following information:
        - [x] Round status: Upcoming, Active, Ended (better copy here?)
        - [x] Appropriate time relation to status: "Starts in _____", "Ends in ______", "Ended ______ ago"
        - [x] Hovering over the time description should show a discrete, human readable timestamp for the appropriate time
        - [x] Funding Token (Show name and/or symbol; clicking should take to Etherscan token site?)
        - [ ] Matching Pool Balance OR the amount of the matching pool that was paid out, if it was
        - [x] Owner address (with Etherscan link?)
    - [x] Matching pool contribution form: iff the Round is Upcoming or Active, show a form allowing the user to make a matching pool contribution; specify an amount, then sign/submit the token approval and `addMatchingFunds` method call txs
    - [ ] Payout contract destination: iff the Round `hasPaidOut`, show the contract address (and transaction hash?) where the payout was made to. Link to Etherescan.
- [x] Round List Page: dependent on #19 
     - [x] ~~route: `/dgrants/rounds/factory/:address` where `:address` is the hex address of a `GrantRoundFactory` contract instance~~ — route: `/dgrants/rounds` (updated with assumption that the Factory is a singleton)
     - [x] Show a list of GrantRound instances deployed by this factory, identified by address (in the future, this will be the Round title as fetched from MetaDat)
     - [x] Show three discrete sections: Active, Upcoming, Ended
     - [x] Sort Grants in each section by: Active: End Date, soonest first; Upcoming: Start Date, soonest first; Ended: End Date, recently ended first
     - [x] Clicking each GrantRound should take the user to the appropriate Grant Detail Page

Additional notes/questions:

* A list of Grants included in this Round is not yet included, because as currently conceived, the list of canonical grants is stored in the metadata
* Should we show a list of matching pool contributions? If so, should we have an event emitted from the `addMatchingFunds` method? Should we have a minimum matching pool contribution threshold?

**Comment by mds1** [comment]
> route: /dgrants/rounds/factory/:address where :address is the hex address of a GrantRoundFactory contract instance

I thought of the Factory as a singleton, similar to the registry. Is this assumption incorrect? If not, we could just have the route be `/dgrants/rounds` and be independent of the factory address. This also mirrors the grant registry URL scheme where the "slug root" lists all the instances, and then you can click into a detail one
