### ISSUE TITLE
disconnect wallet doesn't truly disconnect

### ISSUE THREAD

**Issue by scco** [dcgtc/dgrants#299]
1. when your connected, hover over your top right address + identicon
2. click "disconnect wallet"
3. refresh page - you are still connected

https://user-images.githubusercontent.com/569641/135262752-99dca720-6805-4667-a3f5-7e7b16ba8efb.mov

**Comment by mds1** [comment]
This current behavior is what's expected—you disconnect your wallet from the current session, and when refreshing it uses the `last-wallet` info in localstorage to automatically reconnect on your next visit.

We can easily change this to clear the `last-wallet` data from localstorage if we want to to prevent auto-reconnecting on your next visit, it just depends on the intent of the "disconnect wallet" functionality, e.g. it is supposed to be session-based or permanent?

**Comment by scco** [comment]
image you would logout from paypal , but your back logged int next visit  :)   so i would be not against a change in the current mechanic .
