### ISSUE TITLE
feat: show list of contributors for the matching pool

### ISSUE THREAD

**Issue by thelostone-mc** [dcgtc/dgrants#322]
### Description

- show list of contributors who contribute to matching pool
- order by amount
- show amount

need to sync up with @scco  on design

**Comment by apbendi** [comment]
In addition to rebasing #367 and getting the build passing, the owner of this issue should coordinate with @scco to make sure the design component is implemented using his generalized contributions list component.

**Comment by apbendi** [comment]
@gdixon to look into getting the [matching contributions](https://github.com/dcgtc/dgrants/blob/main/contracts/contracts/GrantRound.sol#L95) added to the subgraph.
