### ISSUE TITLE
Accessing a Grant Round can only be done through the title

### ISSUE THREAD

**Issue by frankchen07** [dcgtc/dgrants#362]
### Description
1. Clicking the image doesn't lead them to the round info.
2. Changing the url does.
3. Clicking on a very specific part of the title does.

https://user-images.githubusercontent.com/7516920/137006895-29fffda6-4a24-4a16-85e3-953958502eff.mp4

**Comment by thelostone-mc** [comment]
Looks like this has been fixed!
![Untitled](https://user-images.githubusercontent.com/5358146/137830989-7853627a-6ce1-4bf3-9898-942610397cfa.gif)
