### ISSUE TITLE
Decide on a CSS approach/framework

### ISSUE THREAD

**Issue by mds1** [dcgtc/dgrants#4]
Context from @phutchins in https://github.com/dcgtc/dcgrants/pull/2#discussion_r665705439:

> We may opt to replace Nightwind and Tailwind but we can leave them for now.
> 
> Our designer @scco is big on simple design without frameworks. If we decided not to use it, it may be more of a completely remove type of thing than a replace with something else so the effort might not be as bad as you think. Our direction right now is to build just enough UI to test/try the platform that we're building so we shouldn't spend time just yet worrying about making it pretty so if we were to wipe the ui in a few weeks and start over it shouldn't mater. I'm currently in between as I have not used Tailwind before and would like to give it a shot. I also would like for it to be relatively easy for people that are not our designer to make additions/changes so a framework might be useful. On the other hand they can make things more complex. I think we can decide this over the next week or two as @scco will be devoting more time to this project a few days from now.

**Comment by octavioamu** [comment]
My recommendation > tailwind 

Well first of all, css framework is a need for any OSS project where many people will be working together and the options always end up in or creating a framework ( a good one could be months of an experienced frontend)  or pick one of the offers around there. The problems on not using a css framework are well know but and I will not spend here the characters but happy to discuss if someone interested.

Tailwind
Been using on some projects and is amazing, some of the arguments 
- utility first make no limits on what you need to create with a less opinionated components styles.
- using the mixings you can create your own main components classes and fit any need.
- using last build tools and approach to get smaller bundles.

**Comment by wildmolasses** [comment]
we've been using tailwind at scopelift for a while. correct me if I'm wrong @mds1 but I think we both enjoy it a lot! and in my experience, tailwind and simple design can coexist :)

**Comment by mds1** [comment]
I'm also on the pro-tailwind side of this decision, for all the reasons mentioned above

@phutchins and @scco—let us know if you have any counterpoints / objections to moving forward with Tailwind, or if we can mark this issue as closed in favor of using Tailwind. Thanks!

**Comment by phutchins** [comment]
We'll be moving forward with tailwind. Closing this issue.
