### ISSUE TITLE
When clicking a grant to view, it is slow to load and no feedback

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#416]
Sometimes when you are on the main page, or the grant list page and click a grant, there is no feedback and a delay before the grant actually loads.

- Identify all of the places that this could potentially happen
- When you click anything in dGrants that takes you to a new page, feedback should be given immediately to let you know that the next page is loading

**Comment by jjwoz** [comment]
@phutchins I am going to move this back into the backlog just because I do not think this is pressing at this time. We could have further discussion about putting a minimum loading time on every spinner in the event that it is loaded so fast there is no indication a new screen was rendered.
