### ISSUE TITLE
Donating to a GrantRound should give feedback and show pending

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#426]
Currently when donating directly to a GrantRound there is no feedback and it may appear that nothing is happening.

- Implement a similar UX flow to what we have in the cart donate process where feedback is immediately given upon actions taken (like clicking donate)

**Comment by mds1** [comment]
Huh, I thought we had implemented this, but on the latest `main` this seems to not be the case. This feels like a big UX issue for contributors, so should this be a GR12 issue?

**Comment by mk1r** [comment]
Oh yes, I think this is mostly done - will push a PR later today (was prioritizing GR12)
