### ISSUE TITLE
Change failure to load whitelist behavior

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#459]
Failure to load the global whitelist should result in the following behavior
- Check for a local cache of the whitelist and use that if it exists
- If no local copy of the whitelist exists, display an error

Additionally we should add a fallback url for the whitelist which could be a different IPFS gateway or http server

**Comment by mds1** [comment]
@gdixon do we currently cache the whitelist or is that a new feature we'd need to add?
