### ISSUE TITLE
Inconsistency when user contribute to more than one grant

### ISSUE THREAD

**Issue by Ajand** [dcgtc/dgrants#470]
After #460 the inconsistency for most users will be fixed. But there is still an inconsistency for users who have contributed to more than one grant. In this picture, the left window is a normal user and the right window is a user who just contributed to 4 grants. As you see it only loads one contribution for the users who contributes to more than one grant.

![Screen Shot 1400-08-09 at 20 12 21](https://user-images.githubusercontent.com/64213712/139593972-cd9762e6-1fa2-4fe0-8bd2-c0916b7a1e14.png)

**Comment by Ajand** [comment]
It seems the problem is caused by grantDonationListener function which will override it's own data before saving them, and the problem is not just for the contributor, but for all users who are online while the transaction is happening. Trying to find a solution for it.

**Comment by phutchins** [comment]
Looks like work here is done.
