### ISSUE TITLE
Now that the MC round has completed, prod should have a back soon page displayed

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#472]
After payouts have completed, the production site ( https://grants.gtcdao.net ) should be taken down and display a page saying that dGrants will be back soon.

This is so that we can focus on making the breaking changes needed and not worry about keeping a production site up to allow us to move quickly.

**Comment by phutchins** [comment]
This should be implemented such that:
- There is an ENV variable called APP_DISABLED which defaults to false
- When APP_DISABLED is set to true, the appDisabled view is displayed
- The appDisabled view should disable loading any data in the data store
- The appDisabled view should show a message stating that dGrants will be back soon as we prepare for the next release
- The appDisabled view should does not need to display the top menu bar or footer

**Comment by mds1** [comment]
@scco Do you want to post a screenshot of the design here, or did you want to write the Vue code yourself and I'll handle the app logic? Either is fine with me!

**Comment by scco** [comment]
i would tackle it like this :

- remove all not needed parts of app
- remove main nav
- copy the template of  /views/404
- add a views/503  and change some text in it like this : 
- load the 503 as default view / home route. 

<img width="630" alt="Bildschirmfoto 2021-11-17 um 17 49 41" src="https://user-images.githubusercontent.com/569641/142245652-c2c1e0c1-5219-457b-a9a6-9e85b37d1d9d.png">

if you need help with styling let me know, but should be good to go without any new design.
