### ISSUE TITLE
Payout Deploy and Script

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#474]
- [ ] Generate payouts
- [ ] Deploy the Merkle Distributor w/ the root
- [ ] Transfer funds to merkle contract
- [ ] Call the bulk payout function on the distributor

@mds1 to build script with input from @gdixon @thelostone-mc on generating the payouts. @phutchins will run the script in production. Generate a doc with the steps for future reference.

**Comment by phutchins** [comment]
Any progress here @thelostone-mc? Shall we hop on a call and push through it?
