### ISSUE TITLE
My Contributions Page

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#483]
Add a new page that will:

- [ ] Fetch and list all of the user's contributions
- [ ] It should be linked in the wallet drop down in the top right
- [ ] It should use generalized contributions list component developed by @scco, and which will also be used in #322. Coordinate with @scco to ensure this is done

#### Open Questions

* What should the route be for this page? One option would be to create a generic route like `/donors/$ADDRESS`, where $ADDRESS would be any valid Ethereum address. The link on the site would then pull this address from the connected wallet, but the route could work with any address supplied.
* Should this page list contributions to Grants **and** to Grant Rounds (i.e. to matching pools)? If so, should those be separated into two sections?
* What should

**Comment by scco** [comment]
frontend is ready to use with static dummy data for @jjwoz to use in his branch 
 
https://github.com/dcgtc/dgrants/tree/contributions-static-frontend-dummy

https://user-images.githubusercontent.com/569641/140490773-0ce1832f-084c-42a7-972a-a89f008e85ab.mov

**Comment by apbendi** [comment]
Looks good @scco! One limitation: it may not be easy/possible to get the matching amounts for a contribution. Remember that a grant can be in any number of rounds— simultaneously and over time— and each round can have it's own matching algo, pool size, etc...

**Comment by jjwoz** [comment]
@scco looks amazing currently working with your branch.

**Comment by apbendi** [comment]
closed with #524
