### ISSUE TITLE
My Grants Page

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#484]
Create a new page that

- [ ] Shows all Grants owned by the currently connected wallet. Ownership is defined by being set as the `owner` property in [grant registry](https://github.com/dcgtc/dgrants/blob/main/contracts/contracts/GrantRegistry.sol#L21).
- [ ] Shows the Grants status as either:
    - [ ] Pending: defined by not being in the whitelist
    - [ ] Approved: defined by being in the whitelist
- [ ] Use the same Grant List component used throughout the site

#### Open Questions

* What should the route be for this page?
* What's the most performant way to fetch this data? Maybe by pulling [create](https://github.com/dcgtc/dgrants/blob/main/contracts/contracts/GrantRegistry.sol#L33) and [update](https://github.com/dcgtc/dgrants/blob/main/contracts/contracts/GrantRegistry.sol#L36) events from The Graph?

**Comment by thelostone-mc** [comment]
@scco question:  Shall I stick to the same layout we have on grants list.
The only difference being , adding a status along to it which says it's not approved ?

@apbendi relying on create event would work. 
I'm not sure update event is required here

**Comment by apbendi** [comment]
@thelostone-mc The update even is needed because the Grant Owner can be updated!

**Comment by thelostone-mc** [comment]
figma link: https://www.figma.com/file/sUQSYyPfooqTcVdajfZm0t/dgrants?node-id=1413%3A6335

The section on the left is what will be built now while the section on the right is the end state which cannot be built now as we to improve our review flow 

What will be built:
- List of grants owned by user
- Details about the grant
- If the grant is in Pending / Approved State


Things which we aren't doing while building this out for now
- Denied / Request Review State
- Disable button for grant owner  
- Additional info on why a grant was denied / not approved

**Comment by apbendi** [comment]
Looks right to me @thelostone-mc. Thanks for the assist @scco

**Comment by thelostone-mc** [comment]
Draft PR: https://github.com/dcgtc/dgrants/pull/494

**Comment by gdixon** [comment]
Closed by #494
