### ISSUE TITLE
Site Loading Performance Triage

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#485]
The site can take a very long time to load, especially (but not only) on a fresh load, and especially (but not only) when loading while a wallet is not connected.

We need to triage this and look for opportunities to get big performance wins. We need to use some kind of profiling/networking tools to analyze where the bottlenecks currently are. Once these are identified, we need to brainstorm and evaluate ways to speed up these issues.

Such improvements might be broken off as separate issues, to be tackled independently of this analysis task. They could include, but are not limited to:

* Frontend optimizations
* Adding a caching layer or proxy server of some kind
* Fetching more data from The Graph instead of from RPC
* Deploying or paying for faster RPC nodes, IPFS endpoints, etc...

**Comment by jjwoz** [comment]
@gdixon from what I can tell something that may be contributing to the performance issue(s) is the calling of `useDataStore` in multiple components. It is responsible for fetching the data from the store. An example is the App component and the Home Component both call this function.
