### ISSUE TITLE
IPFS Loading Speeds and Timeout Improvements

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#486]
- [x] Talk to Fleek team, make sure
   * We're setup with a paid premium account that will give us good speeds
    * They're ready for influx of users during GR12
   * We're following all best practices they recommend
- [ ] Explore backup/alternative IPFS endpoint in case of failures or slowness

**Comment by phutchins** [comment]
We should be good with the new gateway provided by Fleek however we will still put some work into our own IPFS gateway as a backup.

**Comment by apbendi** [comment]
Broke out #548 to track that task. Otherwise this issue is closed with #498
