### ISSUE TITLE
Polygon RPC Endpoint Performance

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#487]
- [x] Talk to Polygon team, make sure
   * We're following all best practices they recommend
   * They're ready for influx of users during GR12
   *  Whether there are any paid services that provide high performance nodes we could use
- [x] Explore backup/alternative endpoints in case of failures or slowness
- [x] Explore ways to degrade gracefully

-------

Tasks derived from research/discussion:

- [x] #508
- [x] #509
- [x] Choose 3rd party node service

**Comment by apbendi** [comment]
@

**Comment by apbendi** [comment]
@phutchins I have a contact or two on the Polygon team I can reach out to start this conversation, unless you/Gitcoin/The DAO has a preferred comms route.

**Comment by thelostone-mc** [comment]
I've got in with the Polygon team as well! Lemme know if you need a hand in initiating a convo here

**Comment by phutchins** [comment]
@apbendi if you would reach out and CC me that would be great. If your contacts don’t respond quickly then we could give @thelostone-mc’s a try.

**Comment by thelostone-mc** [comment]
Based what we've gathered soo far! 

> In general it's recommended to use rpc aggregator https://polygon-rpc.com/ or a dedicated rpc from Infura.

This is what we use and even through polygon-rpc is not rate limited.
the recommendation is to use Alchemy and Moralis.
ITX from Infura is worth considering for handling stuck/dropped transactions.

**Comment by thelostone-mc** [comment]
```
Each function has been called 50 times
rpc https://speedy-nodes-nyc.moralis.io/a2586e6a4965d7035a097eaf/polygon/mainnet
grantsCount {
  slowest: 2463.042792081833,
  fastest: 880.7181670665741,
  avg: 1104.908756608963
}
getAllGrants {
  slowest: 2110.562875032425,
  fastest: 14.368041038513184,
  avg: 1134.7917033147812
}
rpc https://polygon-mainnet.g.alchemy.com/v2/EDGl6ZSI39a9rlwQwfxlWcLsgYkac02v
grantsCount {
  slowest: 3394.519500017166,
  fastest: 967.1819169521332,
  avg: 2018.7956666517257
}
getAllGrants {
  slowest: 3517.3185839653015,
  fastest: 85.7737078666687,
  avg: 1959.7220825338363
}
```
