### ISSUE TITLE
Update IPFS Fetching Endpoint

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#498]
The endpoint used for **fetching** from IPFS should be updated to `https://scopelift.b-cdn.net/ipfs/<cid>/`. The trailing slash after the CID is *required* or the endpoint will 500.

This issue is a spinout from #486

**Comment by apbendi** [comment]
Hey @mk1r this should be a quick one, mind tackling it? Thanks!

**Comment by mk1r** [comment]
sure @apbendi! is it similar to what I did here: https://github.com/dcgtc/dgrants/pull/458
