### ISSUE TITLE
Update The Graph for staging Polygon Deploy

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#512]
- [ ] Update types for metadata changes
 - [ ] Update new events/new event parameters
 - [ ] Point to the newly deployed staging contracts on Polygon
 - [ ] Re-enable in the app itself

**Comment by mds1** [comment]
@thelostone-mc @gdixon can we also do the Rinkeby deploy in this same issue?

**Comment by thelostone-mc** [comment]
Oh @mds1 did we get the contracts deployed on rinkeby as well ?

**Comment by mds1** [comment]
Yes we did, and based on https://github.com/dcgtc/dgrants-subgraph/pull/7 I can see you already found the addresses!
