### ISSUE TITLE
Default network and contract addresses should be configurable by ENV variable

### ISSUE THREAD

**Issue by phutchins** [dcgtc/dgrants#514]
This change would allow supporting different environment deployments like production vs staging where different sets of contracts are used and potentially different networks.

ENV Variables to add:
- DEFAULT_CHAIN_ID (int)
- GRANT_REGISTRY_CONTRACT (string)
- GRANT_ROUND_MANAGERS (array[string]) (comma separated in the ENV variable)
- SWAP_CONTRACT (string)
- SUBGRAPH_URL (string)

All of these should have sane defaults.

**Comment by apbendi** [comment]
Agree this would be nice, but it also feels like it's lower priority/on the bubble for GR12, given the lots of other stuff that needs to get done 😅

**Comment by phutchins** [comment]
While I agree, the repercussion on not having this done means that we will can only auto deploy to a single environment. This may be fine while we are only working out of the staging environment but in about a week (or less) once we deploy the production environment, we will break staging.

**Comment by phutchins** [comment]
Added SUBGRAPH_URL as well.
