### ISSUE TITLE
Sporadic Very Slow Responses From The Graph

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#538]
In repeatedly testing #534, I occasionally saw extremely long load times, i.e. the loading spinner persisted on the page for 5-10 seconds or more. Anecdotally, I seemed to see this perhaps every 3-6 times I cleared local store and did a hard refresh of the page.

Digging into this a bit more, it seems to be caused by sporadic hanging requests to The Graph, as demonstrated below:

![long-graph-response](https://user-images.githubusercontent.com/1479802/143918434-5636a201-5c08-4fe7-a1d8-91cbf1738e7a.gif)

A few thoughts on this:

1. Is there anything we're doing that might be causing this? For example, is this a weird edge case query of some kind— querying for empty data or for a block number that The Graph hasn't loaded or something like this (totally spitballing, just wondering if anything about the nature of our request could be causing it).
2. Do we have a contact with The Graph we can reach out to about this— perhaps there is something about our graph configuration that might be causing it, or a paid tier we can upgrade to that would reduce the likelihood of this issue, etc...
3. Is there anything we can do to mitigate the impact of this for users, if there's no way to prevent it from happening sporadically in production. Perhaps, for example, timeout our request client side after 5000 ms and retry, or something along these lines?

**Comment by apbendi** [comment]
Here are some screenshots I took about the request in question, in case they are helpful:
<img width="378" alt="Screen Shot 2021-11-29 at 12 08 17 PM" src="https://user-images.githubusercontent.com/1479802/143918999-7ac54067-f0f5-4079-bce9-5502a5d19572.png">
<img width="750" alt="Screen Shot 2021-11-29 at 12 07 59 PM" src="https://user-images.githubusercontent.com/1479802/143919001-fd5a1a38-3562-4cc4-9b43-0d8487fbdab8.png">
<img width="988" alt="Screen Shot 2021-11-29 at 12 04 50 PM" src="https://user-images.githubusercontent.com/1479802/143919002-c0094395-8cd8-4edb-bcf1-bfc2e3cb8371.png">

**Comment by apbendi** [comment]
screenshots form another very slow run:
<img width="446" alt="Screen Shot 2021-11-29 at 1 22 02 PM" src="https://user-images.githubusercontent.com/1479802/143922113-8669489c-d2a0-4b72-8c81-590ce6181d1f.png">
<img width="453" alt="Screen Shot 2021-11-29 at 1 21 57 PM" src="https://user-images.githubusercontent.com/1479802/143922114-447113fb-cb42-41bc-9ed4-394f98c10b3a.png">
<img width="848" alt="Screen Shot 2021-11-29 at 1 21 51 PM" src="https://user-images.githubusercontent.com/1479802/143922115-3f7d0833-762d-4bec-9cad-62e941bd4943.png">
<img width="846" alt="Screen Shot 2021-11-29 at 1 21 46 PM" src="https://user-images.githubusercontent.com/1479802/143922116-ebfd74e4-6077-4e88-b16d-65b635f433e5.png">
<img width="395" alt="Screen Shot 2021-11-29 at 1 21 15 PM" src="https://user-images.githubusercontent.com/1479802/143922117-43c773ba-f942-4ed2-abcf-8dbe2d98c127.png">

**Comment by azf20** [comment]
Hey @apbendi are you still seeing this slow loading? There were some changes on the Hosted Service proxy that fixed some connection issues. If you are still having issues, happy to dig in here

**Comment by apbendi** [comment]
Thanks @azf20, this appears to be resolved. I've not seen it in testing or in day-to-day usage of the app, now in prod for several days.
