### ISSUE TITLE
bug: "My Contributions" page gets stuck if you load it without a wallet connected

### ISSUE THREAD

**Issue by mds1** [dcgtc/dgrants#545]
If you navigate to the route added in #524 without a wallet connected, it spins forever. This could happen if someone reopens a browser or something. We should instead show a button that tells the user they need to connect their wallet to view this page

**Comment by apbendi** [comment]
Update: this also seems to be happening in the production environment, at least at the moment. Current conditions might be related, i.e. the Round has not started and there are no contributions globally.

**Comment by apbendi** [comment]
closed by #553
