### ISSUE TITLE
Contributions are slow to fully load

### ISSUE THREAD

**Issue by mk1r** [dcgtc/dgrants#562]
Grant round contributions are slow to load completely, certain data loads fine, but the logo and name take longer and sometimes are only loaded after leaving the grant round page and navigating back to it

related to #560

**Comment by mds1** [comment]
@mk1r do you have more specific data on this issue, similar to how @apbendi documented #538? More detailed issue reports will make things easier to reproduce and resolve, especially if we don't tackle this for a few weeks and forget what you meant here:
- What network(s) did you see this on on?
- Is it subgraph requests or RPC requests?
- When you say "certain data" loads fine, which data is that? Sounds like this issue just means the logo and name are slow, i.e. the metadata?

**Comment by apbendi** [comment]
Issue was metadata loading. Closing for now and will keep an eye on Fleek performance.
