### ISSUE TITLE
Dune Analytics Dashboard

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#572]
The dgrants contracts are now available for querying in Dune Analytics.

<img width="409" alt="Screen Shot 2021-12-06 at 11 20 10 AM" src="https://user-images.githubusercontent.com/1479802/144885327-936856d8-ef03-4955-8b3d-0852986e39df.png">

We should create queries to show:

- [x] Total Dai donated to all grants
- [x] Unique addresses making donations
- [ ] ... more? @phutchins would love your thoughts here

It would be great to visualize some of this over time as well, but starting with just the queries would be great.

**Comment by apbendi** [comment]
A very simple query for showing total donations: https://dune.xyz/queries/282291

**Comment by frankchen07** [comment]
I can take a look at this. What's timeline here.

**Comment by frankchen07** [comment]
https://dune.xyz/fronk/gitcoin-dgrants-gr12 - mark as resolved

would love to talk more about what else ya'll would like to see.

Would like a check on how we are saving unique IDs of folks contributing here for accuracy on one of the queries.

**Comment by phutchins** [comment]
This is great @frankchen07! You hit all the points that I was looking for. We'll need to do some more work to get much more than this. We can create another issue for getting data on user flow and such.
