### ISSUE TITLE
Fix CI to add `INFURA_ID` environment variable

### ISSUE THREAD

**Issue by mds1** [dcgtc/dgrants#62]
This is now needed because we fork mainnet for testing as of #61

**Comment by wildmolasses** [comment]
Hi @phutchins can you add an INFURA_ID to our repo secrets? https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

if you could just confirm the name of the secret and then assign this issue back to me, that would be awesome!

**Comment by phutchins** [comment]
Done!
