### ISSUE TITLE
Test Coverage For GrantRound Deployment Revert Cases

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#64]
The revert cases in the `GrantRound` constructor should be explicitly tested.

**Comment by mds1** [comment]
On a related note, I think we start using the `coverage` script to (1) make sure we are near 100% coverage, and (2) make sure coverage doesn't decrease in PRs. I think there's a way to get coverage to run and be reported in a a PR as part of CI? cc @wildmolasses

**Comment by apbendi** [comment]
closed by #59
