### ISSUE TITLE
Allow Arbitrary Input Tokens for Swap and Donate

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#71]
Current implementation requires an existing pool for the pair. Determine how to do arbitrary "paths" between tokens for Uniswap v3. Implement this in current contracts, and/or alongside the bulk checkout functionality.

**Comment by mds1** [comment]
https://docs.uniswap.org/protocol/guides/swaps/multihop-swaps

**Comment by thelostone-mc** [comment]
It looks like encoding can be done on the frontend via this
https://github.com/Uniswap/uniswap-v3-periphery/blob/9ca9575d09b0b8d985cc4d9a0f689f7a4470ecb7/test/shared/path.ts

Got that from https://soliditydeveloper.com/uniswap3

![image](https://user-images.githubusercontent.com/5358146/128014473-20bc9684-9e21-49d8-b997-48fe95b70fd1.png)
