### ISSUE TITLE
does `yarn dev` expose a RPC url?

### ISSUE THREAD

**Issue by owocki** [dcgtc/dgrants#81]
does `yarn dev` expose a RPC url?

if so what is it?

looks like all dgrants are posted to a local RPC, but i dont see an address in the terminal when i run `yarn app dev`, and i dont see in the docs how to run this

**Comment by mds1** [comment]
When you run `yarn dev` from the root it stands up a local chain at `http://127.0.0.1:8545/` which forks the mainnet. You can see this below where it says `[0] Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/`

![image](https://user-images.githubusercontent.com/17163988/128084956-d0547d5d-f32f-4b28-a873-0e7b033e6841.png)

**Comment by apbendi** [comment]
Closing this based on @mds1 response. Please feel free to reopen if needed @owocki!
