### ISSUE TITLE
[PLACEHOLDER] UI Component List

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#83]
@scco to generate list of un-styled UI components that need to be implemented so that he can style them

**Comment by scco** [comment]
this list is not complete / not ordered by priority.

ICONS ( graham will look at this )
contribute to fusion ( https://github.com/scco/fusion )  ( richards icon system )  so icons can be vue components
and add it as a dependency to dgrants, add an example how to add an icon as inline-svg styleable with stroke color.

IDENTICONS
adding jazzicon ( identicons of metamask ) as a dependency and provide an example how to embed as an image.

DROPDOWN
adding a dropdown, that can be searchable by given values ( e.g. for tokens ) and a vertical scroll bar.  when a user clicks in the search-field, values in list dissapear what not match the search term.

<img width="282" alt="Bildschirmfoto 2021-08-04 um 17 50 13" src="https://user-images.githubusercontent.com/569641/128212729-70c96983-cb65-4a73-a26e-de3273b8158f.png">

TAB-GROUP ( not tab BAR - just the "tabs" itself )
creating a group of items what can have optional numeric or string values , where one item can be "active"
<img width="285" alt="Bildschirmfoto 2021-08-04 um 17 55 19" src="https://user-images.githubusercontent.com/569641/128213623-99257fab-e0fd-42aa-b361-d6a0ebf2db98.png">

BREADCRUMB
creating a list of items split by a seperator ( arrow icon ) where some can have links , but some not. 
<img width="209" alt="Bildschirmfoto 2021-08-04 um 17 59 04" src="https://user-images.githubusercontent.com/569641/128214221-c7f52f4d-62d8-4965-860b-be1cde34728a.png">

TEXT AREA
creating a text area , with a min height, that can get more rows / grow verticaly when user write more text  ( think facebook came up with this a long time ago )

NAV BAR
the nav bars elements : 
- a right logo with an arrow , that on click should open and close a menu what can have multible groups of lists seperated with a horizontal line. i need the functionality to toggle this menu + close it when its open by click "everywhere" on screen.
- a search input what needs to show some results ( i think we can skip this for now ? )
- a cart that should link to a cart view and have a value of items in cart 
- a logged-in area for users to display a trunciated eth address + an identicon + an arrow. this area should be clickable to toggle another menu with the same behaviours ( but more complex inner content ) than the other nav menu .  ( close on click anywhere on screen,  toggle on click anywhere on the group of address+img+arrow .     inside this menu there need to be a logout() or / switchwalletprovider() link. 
- a not-logged-in-area to display a "connect to wallet" 

IMAGE SLIDER
bring in a reliable modern 100% full width image slider that is mobile friendly to slide a set of dummy images what have a format of 1920x1200 .


i think it would be a nice idea, to load all that components into a single preview file  ( i did a  ui.vue ) so we can see all that components and combination of components in one place with examples how to embed.

think thats it for now, theres way more to cover but maybe a good starting point.

**Comment by thelostone-mc** [comment]
Closing this out as we've documented this in other issues @apbendi
