### ISSUE TITLE
Extend GrantRoundManager from Uniswap v3's SwapRouter

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#99]
Making the `GrantRoundManager` inherit from `SwapRouter` (#74) would remove approvals and transfers that are currently needed.

Inheriting from SwapRouter means we'd become a custom v3 router, and users would have to trust (or verify by inspected verified source code) that we did not modify the router functionality in some malicious or unsafe way.

**Comment by mk1r** [comment]
reference: PR #109 and #120
